In [3]:
using LinearAlgebra
using InvertedIndices
Y = [1/(0.01938+0.05917im)+1/(0.05403+0.22304im) -1/(0.01938+0.05917im) 0.0+0.0im 0.0+0.0im -1/(0.05403+0.22304im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;-1/(0.01938+0.05917im) 1/(0.01938+0.05917im)+1/(0.04699+0.19797im)+1/(0.05811+0.17632im)+1/(0.05695+0.17388im) -1/(0.04699+0.19797im) -1/(0.05811+0.17632im) -1/(0.05695+0.17388im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im -1/(0.04699+0.19797im) 1/(0.04699+0.19797im)+1/(0.06701+0.17103im) -1/(0.06701+0.17103im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im -1/(0.05811+0.17632im) -1/(0.06701+0.17103im) 1/(0.05811+0.17632im)+1/(0.06701+0.17103im)+1/(0.01335+0.04211im)+1/(0.0+0.20912im)+1/(0.0+0.55618im) -1/(0.01335+0.04211im) 0.0+0.0im -1/(0.0+0.20912im) 0.0+0.0im -1/(0.0+0.55618im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;-1/(0.05403+0.22304im) -1/(0.05695+0.17388im) 0.0+0.0im -1/(0.01335+0.04211im) 1/(0.05403+0.22304im)+1/(0.05695+0.17388im)+1/(0.01335+0.04211im)+1/(0.0+0.25202im) -1/(0.0+0.25202im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.25202im) 1/(0.0+0.25202im)+1/(0.09498+0.1989im)+1/(0.12291+0.25581im)+1/(0.06615+0.13027im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.09498+0.1989im) -1/(0.12291+0.25581im) -1/(0.06615+0.13027im) 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.20912im) 0.0+0.0im  0.0+0.0im 1/(0.0+0.20912im)+1/(0.0+0.17615im)+1/(0.0+0.11001im) -1/(0.0+0.17615im) -1/(0.0+0.11001im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.17615im) 1/(0.0+0.17615im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.55618im) 0.0+0.0im 0.0+0.0im -1/(0.0+0.11001im) 0.0+0.0im 1/(0.0+0.55618im)+1/(0.0+0.11001im)+1/(0.03181+0.0845im)+1/(0.12711+0.27038im) -1/(0.03181+0.0845im) 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.12711+0.27038im);0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.03181+0.0845im) 1/(0.03181+0.0845im)+1/(0.08205+0.19207im) 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.08205+0.19207im);0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.09498+0.1989im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 1/(0.09498+0.1989im) 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.12291+0.25581im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 1/(0.22092+0.19988im)+1/(0.12291+0.25581im) -1/(0.22092+0.19988im) 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.06615+0.13027im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.22092+0.19988im) 1/(0.22092+0.19988im)+1/(0.06615+0.13027im)+1/(0.17093+0.34802im) -1/(0.17093+0.34802im);0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.12711+0.27038im) -1/(0.08205+0.19207im) 0.0+0.0im 0.0+0.0im -1/(0.17093+0.34802im) 1/(0.12711+0.27038im)+1/(0.08205+0.19207im)+1/(0.17093+0.34802im)]
Sg = [2.324-0.169im,0.40+0.424im,0.0+0.234im,0.0+0.0im,0.0+0.0im,0.0+0.122im,0.0+0.0im,0.0+0.174im,0.0+0.0im,0.0+0.0im,0.0+0.0im,0.0+0.0im,0.0+0.0im,0.0+0.0im]
Sd = [0.0+0.0im,0.217+0.127im,0.942+0.19im,0.478-0.039im,0.076+0.016,0.112+0.075im,0.0+0.0im,0.0+0.0im,0.292+0.166im,0.09+0.058im,0.035+0.018im,0.061+0.016im,0.135+0.058im,0.149+0.05im]
S = Sg-Sd
PQ = [4,5,7,9,10,11,12,13,14]
Swing=[1]
PV = [2,3,6,8]
N = 14
V = [1.06+0.0im,1.045+0.0im,1.01+0.0im,1.0+0.0im,1.0+0.0im,1.07+0.0im,1.0+0.0im,1.09+0.0im,1.0+0.0im,1.0+0.0im,1.0+0.0im,1.0+0.0im,1.0+0.0im,1.0+0.0im]
Vm= [1.06,1.045,1.01,0,0,1.07,0,1.09,0,0,0,0,0,0]
#======================================================Function Declaration==================================================#
function sudut(V)
    # menghitung sudut bilangan kompleks dalam radian
    x=real(V)
    y=imag(V)
    θ=atan.(y./x)
    return θ
end
function radiankederajat(rad)
    hasil = rad.*180/pi
    return hasil
end
function Current(N,Y,V) #menghitung arus berdasarkan pers 11
        In = zeros(ComplexF64,N,1)
        for k in 1:N
            for n in 1:N
                In[k] = In[k] + Y[k,n]*V[n]
            end
        end
        return In
        end
function Missmatch(i,V,S,PV,PQ,N) # missmatch berdasarkan pers 10 dan 24
        f = zeros(Float64,2*N,1)
        for k in PV                      #bus PV
            f[2*k-1] = real(conj(V[k])*i[k]) - real(S[k])
            f[2*k] = abs(V[k])^2 - Vm[k]^2
        end
        for k in PQ                     #bus PQ
            f[2*k-1] = real(conj(V[k])*i[k]- S[k])
            f[2*k] = imag(conj(V[k])*i[k] + S[k])
        end
        f = f[Not(1:2)]
        return f
        end
function Jacobian(V,i,Y,N,PQ,PV)
        J = zeros(Float64,2*N,2*N)
    for k in PV               #bus PV perhitungan jacobian berdasarkan pers  28,29,30,31
            for n in 1:N
                if k!=n
                #off diagonal
                    J[2*k-1,n] = real(conj(V[k])*Y[k,n])
                    J[2*k,n] = 0                                #terhadap V real
                    J[2*k-1,N+n] =real(conj(V[k])*1im*Y[k,n])
                    J[2*k,N+n] = 0                               #terhadap V imag
                else
                #diagonal
                    J[2*k-1,n] = real(i[k]+conj(V[k])*Y[k,n])
                    J[2*k,n] = 2*real(V[k])                       #terhadap V real
                    J[2*k-1,N+n] =real(-1im*i[k]+conj(V[k])*1im*Y[k,n])
                    J[2*k,N+n] = 2*imag(V[k])                      #terhadap V imag
                end
            end
        end
        for k in PQ                #bus PQ perhitungan jacobian berdasarkan pers 14,15,18,19
            for n in 1:N
                if k!=n
                #off diagonal
                    J[2*k-1,n] = real(conj(V[k])*Y[k,n])
                    J[2*k,n] = imag(conj(V[k])*Y[k,n])          #terhadap V real
                    J[2*k-1,N+n] =real(conj(V[k])*1im*Y[k,n])
                    J[2*k,N+n] = imag(conj(V[k])*1im*Y[k,n])    #terhadap V imag
                else
                #diagonal
                    J[2*k-1,n] = real(i[k]+conj(V[k])*Y[k,n])
                    J[2*k,n] = imag(i[k]+conj(V[k])*Y[k,n])     #terhadap V real
                    J[2*k-1,N+n] =real(-1im*i[k]+conj(V[k])*1im*Y[k,n])
                    J[2*k,N+n] = imag(-1im*i[k]+conj(V[k])*1im*Y[k,n])  ##terhadap V imag
                end
            end
        end
        J = J[Not(1:2), Not(1,N+1)] # hasil jacobian dengan nilai bus 1 tidak ditampilkan
        return J
        end
function S_cal(i,V,PV,PQ,N)       #nilai daya
        Scal = zeros(Float64,2*N,1)
    for k in PV
            Scal[2*k-1] = real(conj(V)[k]*i[k])
            Scal[2*k] = imag(conj(V)[k]*i[k])
        end
        for k in PQ
            Scal[2*k-1] = real(conj(V)[k]*i[k])
            Scal[2*k] = imag(conj(V)[k]*i[k])
        end
        Scal = Scal[Not(1:2)]
        return Scal
        end
function update_teg(V,Δv)
    ΔV = zeros(ComplexF64,N,1)
     for k in PV
    ΔV[k] = Δv[2*k-(k+1)]+Δv[12+k]*1im
    end
    for k in PQ
    ΔV[k] = Δv[2*k-(k+1)]+Δv[12+k]*1im
    end
V = V+ΔV
    return V
end
#####################################################iterasi##############################################################
H = 1
jumlah_iterasi = 0
 while H > 5e-5
 i = Current(N,Y,V)
 s = S_cal(i,V,PV,PQ,N)
 f = Missmatch(i,V,S,PV,PQ,N)
global H = maximum(abs.(f))
 j = Jacobian(V,i,Y,N,PQ,PV)
 Δv = -inv(j)*f 
 V = update_teg(V,Δv)
 θ = radiankederajat(sudut(V))
 global jumlah_iterasi += 1
  @time println(jumlah_iterasi)
   end

1
  0.002829 seconds (26 allocations: 672 bytes)
2
  0.000875 seconds (137 allocations: 10.375 KiB)
3
  0.000263 seconds (24 allocations: 800 bytes)
4
  0.000282 seconds (24 allocations: 896 bytes)


In [10]:
s

26-element Vector{Float64}:
  0.18300123856719513
 -0.3131162332444899
 -0.9420000579265599
 -0.06212523716251553
 -0.47800002260697694
 -0.039001112115264316
 -0.09199937346353532
 -1.0033901299520698e-6
 -0.11200182872448362
 -0.3603797284674856
  2.9609915885267e-6
 -2.421717547160334e-6
 -5.880368683097714e-7
 -0.3213803454396035
 -0.29200266747403997
  0.16599669931214717
 -0.09000089910901794
  0.057998745436719214
 -0.0349981712102742
  0.01799649895434681
 -0.06099847063655117
  0.01599751137436435
 -0.13499689386628425
  0.05799630816391417
 -0.1490010464629899
  0.04999782579938321

In [14]:
S

14-element Vector{ComplexF64}:
               2.324 - 0.169im
 0.18300000000000002 + 0.297im
              -0.942 + 0.04400000000000001im
              -0.478 + 0.039im
              -0.092 + 0.0im
              -0.112 + 0.047im
                 0.0 + 0.0im
                 0.0 + 0.174im
              -0.292 - 0.166im
               -0.09 - 0.058im
              -0.035 - 0.018im
              -0.061 - 0.016im
              -0.135 - 0.058im
              -0.149 - 0.05im

In [2]:
Y = [1/(0.01938+0.05917im)+1/(0.05403+0.22304im) -1/(0.01938+0.05917im) 0.0+0.0im 0.0+0.0im -1/(0.05403+0.22304im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;-1/(0.01938+0.05917im) 1/(0.01938+0.05917im)+1/(0.04699+0.19797im)+1/(0.05811+0.17632im)+1/(0.05695+0.17388im) -1/(0.04699+0.19797im) -1/(0.05811+0.17632im) -1/(0.05695+0.17388im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im -1/(0.04699+0.19797im) 1/(0.04699+0.19797im)+1/(0.06701+0.17103im) -1/(0.06701+0.17103im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im -1/(0.05811+0.17632im) -1/(0.06701+0.17103im) 1/(0.05811+0.17632im)+1/(0.06701+0.17103im)+1/(0.01335+0.04211im)+1/(0.0+0.20912im)+1/(0.0+0.55618im) -1/(0.01335+0.04211im) 0.0+0.0im -1/(0.0+0.20912im) 0.0+0.0im -1/(0.0+0.55618im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;-1/(0.05403+0.22304im) -1/(0.05695+0.17388im) 0.0+0.0im -1/(0.01335+0.04211im) 1/(0.05403+0.22304im)+1/(0.05695+0.17388im)+1/(0.01335+0.04211im)+1/(0.0+0.25202im) -1/(0.0+0.25202im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.25202im) 1/(0.0+0.25202im)+1/(0.09498+0.1989im)+1/(0.12291+0.25581im)+1/(0.06615+0.13027im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.09498+0.1989im) -1/(0.12291+0.25581im) -1/(0.06615+0.13027im) 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.20912im) 0.0+0.0im  0.0+0.0im 1/(0.0+0.20912im)+1/(0.0+0.17615im)+1/(0.0+0.11001im) -1/(0.0+0.17615im) -1/(0.0+0.11001im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.17615im) 1/(0.0+0.17615im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.0+0.55618im) 0.0+0.0im 0.0+0.0im -1/(0.0+0.11001im) 0.0+0.0im 1/(0.0+0.55618im)+1/(0.0+0.11001im)+1/(0.03181+0.0845im)+1/(0.12711+0.27038im) -1/(0.03181+0.0845im) 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.12711+0.27038im);0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.03181+0.0845im) 1/(0.03181+0.0845im)+1/(0.08205+0.19207im) 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.08205+0.19207im);0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.09498+0.1989im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 1/(0.09498+0.1989im) 0.0+0.0im 0.0+0.0im 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.12291+0.25581im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 1/(0.22092+0.19988im)+1/(0.12291+0.25581im) -1/(0.22092+0.19988im) 0.0+0.0im;0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.06615+0.13027im) 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.22092+0.19988im) 1/(0.22092+0.19988im)+1/(0.06615+0.13027im)+1/(0.17093+0.34802im) -1/(0.17093+0.34802im);0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im -1/(0.12711+0.27038im) -1/(0.08205+0.19207im) 0.0+0.0im 0.0+0.0im -1/(0.17093+0.34802im) 1/(0.12711+0.27038im)+1/(0.08205+0.19207im)+1/(0.17093+0.34802im)]


14×14 Matrix{ComplexF64}:
  6.02503-19.4981im  -4.99913+15.2631im  …       0.0+0.0im
 -4.99913+15.2631im   9.52132-30.3547im          0.0+0.0im
      0.0+0.0im      -1.13502+4.78186im          0.0+0.0im
      0.0+0.0im      -1.68603+5.11584im          0.0+0.0im
  -1.0259+4.23498im  -1.70114+5.19393im          0.0+0.0im
      0.0+0.0im           0.0+0.0im      …       0.0+0.0im
      0.0+0.0im           0.0+0.0im              0.0+0.0im
      0.0+0.0im           0.0+0.0im              0.0+0.0im
      0.0+0.0im           0.0+0.0im         -1.42401+3.02905im
      0.0+0.0im           0.0+0.0im         -1.88088+4.40294im
      0.0+0.0im           0.0+0.0im      …       0.0+0.0im
      0.0+0.0im           0.0+0.0im              0.0+0.0im
      0.0+0.0im           0.0+0.0im         -1.13699+2.31496im
      0.0+0.0im           0.0+0.0im          4.44188-9.74696im